name: build

on: [push, pull_request]

env:
  FORCE_COLOR: 3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '15.2.0'
      - run: yarn --frozen-lockfile
      - run: yarn prettier-check
      - run: yarn build
      - run: yarn eslint
      - run: yarn test
      - run: yarn nyc report --reporter json
      - run: 'bash <(curl -s https://codecov.io/bash)'
      - name: release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release
